import os
import shutil
import toml
import rasterio as rio
import numpy as np
from rasterio.warp import Resampling, transform, reproject
from typing import Dict


def set_up_directories(model_settings: Dict) -> None:
    """
    This function sets up the necessary directory structure for the generated products.
    :param model_settings: Model settings read from the settings.toml file
    :return: Void
    """

    for value in model_settings["product_directories"]:
        if not os.path.exists(model_settings["product_directories"][value]):
            os.mkdir(model_settings["product_directories"][value])

    return


def parse_model_settings(path_to_model_settings: str) -> Dict:
    """
    This function parses the model settings from the settings.toml file.
    To run the model under different conditions, change the values in settings.toml file.
    :param path_to_model_settings: Path to settings.toml file
    :return: Model Settings dictionary
    """

    model_settings = toml.load(path_to_model_settings)

    return model_settings


def load_raster_as_array(path_to_raster: str) -> np.ndarray:
    """
    This function uses Rasterio to load the VIIRS raster as an Numpy array.
    :param path_to_raster: Path to the VIIRS raster to be used for skyglow calculation
    :return raster: VIIRS raster as a Numpy array
    """

    with rio.open(path_to_raster, mode="r") as source:
        raster = source.read(1)

        source.close()

    return raster


def write_raster_reprojection(
    path_to_write: str, epsg_code: str, metadata: Dict, source: rio.DatasetReader
) -> None:
    """
    This function writes the reprojected raster to disk.
    :param path_to_write: Path to which the raster is to be written to
    :param source: Source projection raster (original VIIRS, before reprojection)
    :param metadata: Source projection raster metadata.
    :param epsg_code: Coordinate system code
    :return: Void
    """

    with rio.open(path_to_write, mode="w", **metadata) as dst:
        reproject(
            source=rio.band(source, 1),
            destination=rio.band(dst, 1),
            src_transform=source.transform,
            src_crs=source.crs,
            dst_transform=transform,
            dst_crs=epsg_code,
            resampling=Resampling.nearest,
        )

    return


def apply_decay_function(
    model_settings: Dict, distance_kernel: np.ndarray
) -> np.ndarray:
    """
    This function applies the skyglow decay function to the distance kernel.
    :param model_settings: Model settings dictionary generated by reading the settings.toml file
    :param distance_kernel: Array of distances from the center of the array
    :return: Array with the decay function applied to it.
    """

    return model_settings["parameters"]["decay_constant"] * np.exp(
        model_settings["parameters"]["decay_exponent"] * (distance_kernel / 1000)
    )


def compute_frequency_shifts(array: np.ndarray) -> np.ndarray:
    """
    This function computes the frequency shift of a given array (e.g. VIIRS raster or distance kernel),
    and hence takes the array from spatial domain into a frequency domain.
    :param array: Array in spatial domain
    :return: Frequency shifted array
    """
    frequency = np.fft.fft2(array)
    frequency_shift = np.fft.fftshift(frequency)

    return frequency_shift


def compute_inverse_frequency_shifts(
    combined_frequency_shift: np.ndarray,
) -> np.ndarray:
    """
    This function computes the inverse frequency shift of a given array and transforms the
    combined VIIRS and segment kernel, from frequency domain back into spatial domain.
    :param combined_frequency_shift: Combined Frequency Shift of distance kernel and VIIRS image
    :return inverse_frequency_shift: Inverse of the combined Frequency Shift
    """

    inverse_frequency = np.fft.ifft2(combined_frequency_shift)
    inverse_frequency_shift = np.abs(np.fft.ifftshift(inverse_frequency))

    return inverse_frequency_shift


def purge_intermediates(
    preprocessed_rasters_path: str, intermediates_path: str
) -> None:
    """
    This function purges the intermediate segment rasters created during skyglow calculation.
    :param preprocessed_rasters_path: Path to preprocessed raster directory
    :param intermediates_path: Path to intermediate products directory
    :return: Void
    """

    if os.path.exists(preprocessed_rasters_path):
        shutil.rmtree(preprocessed_rasters_path)

    if os.path.exists(intermediates_path):
        shutil.rmtree(intermediates_path)

    return
